# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27edbb2bb78886e266644e0c96752473c217085e645e092ca53f5a507711afde13e31c5b35a899da18731091e481166485befd2a951f6d29dfc8caa5f5adbef9

test:
  secret_key_base: 8e5601b7dc485e76ffc2622b5a8f9656eb360e14d9406aa3536534a68c3df8f9a95324a37b96f9afcfb1108e968e4b3c9373fd9048f39e3695692050915045e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
